[default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.13"
gas_reports = ["DittoMachine"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config
