on: [push]

name: test

env:
  SOLCVER: 0.8.13

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test --via-ir -vvv

      - name: Slither static analyser
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
